---
kind: pipeline
type: docker
name: bullseye build

steps:
  - name: build bullseye
    image: registry.fluves.net/drone/saga-watem/build-bullseye
    commands:
      - dch --newversion $(dpkg-parsechangelog --show-field Version)+$DRONE_BUILD_NUMBER "Automated build for $DRONE_COMMIT~bullseye"
      - debuild -b -us -uc -j8
      - mkdir ../package
      - mv ../*saga*deb ../package
  - name: rsync-apt
    image: drillster/drone-rsync
    settings:
      hosts:
        - ijzer
      user: docs
      key:
         from_secret: ssh-key
      source: package/*.deb
      target: /appdata/static/apt/bullseye/amd64
    when:
      branch:
        - master
        - saga-watem
        - drone
      event:
        exclude:
          - pull_request
---
kind: pipeline
name: windows build
platform:
  os: windows
  version: "1809"
steps:
  - name: build dll
    image: registry.fluves.net/drone/saga-watem/build-windows
    environment:
      SAGA: c:\saga\saga-8.2.1_x64
    commands:
    - mkdir build
    - cd build
    - cmake .. -A x64
    - ../ci/build-win.bat
    - dir release/*
  - name: publish dll on release
    image: registry.fluves.net/test/drone-plugin-windows
    settings:
      api_key:
        from_secret: release_token
      base_url: https://git.fluves.net
      files: build/release/*.dll
      prerelease: true
      note: automatic build
      title: ${DRONE_TAG}
    when:
      event: [tag]



# ---
#kind: pipeline
# name: focal build
# 
# steps:
#   - name: build focal
#     image: registry.fluves.net/drone/saga-watem/build-focal
#     commands:
#       - cd saga-gis
#       - apt install -y dh-python
#         # not working as debian is unfortunately not in the main dir
#         #- gbp dch --snapshot --ignore-branch --snapshot-number=$DRONE_BUILD_NUMBER
#         # Alternative version
#       - dch --newversion $(dpkg-parsechangelog --show-field Version)+$DRONE_BUILD_NUMBER "Automated build for $DRONE_COMMIT~focal"
#       - debuild -b -us -uc -j8
#       - mkdir ../package
#       - mv ../*saga*deb ../package
# 
#   - name: rsync-apt
#     image: drillster/drone-rsync
#     settings:
#       hosts:
#         - ijzer
#       user: docs
#       key:
#          from_secret: ssh-key
#       source: package/*.deb
#       target: /appdata/static/apt/amd64
#     when:
#       branch:
#         - master
#         - saga-watem
#         - drone
#       event:
#         exclude:
#           - pull_request
# 
---
kind: pipeline
type: docker
name: reindex repo
depends_on:
  # - focal build
- bullseye build

steps:
  # copy all packages from repo and rebuild index
  - name: Update repo
    image: registry.fluves.net/drone/cn_ws/debian11-build
    environment:
      GPG_KEY:
         from_secret: gpg-key
      SSH_KEY:
          from_secret: ssh-key
      DEBFULLNAME: "Fluves Drone CI"
      DEBEMAIL: donotreply@fluves.net
    commands:
      - mkdir -p ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa
      - echo "$GPG_KEY" | gpg --import
      - mkdir apt-repo && cd apt-repo
      - rsync -az -e "ssh -p 22 -o StrictHostKeyChecking=no" docs@ijzer:/appdata/static/apt/amd64 .
      - apt-ftparchive packages amd64 > Packages
      - gzip -c Packages > Packages.gz
      - apt-ftparchive release . > Release
      - gpg --clearsign -o InRelease Release
      - gpg -abs -o Release.gpg Release
      - rsync -av . docs@ijzer:/appdata/static/apt/
      - cd .. && rm -rf apt-repo
      - mkdir apt-repo && cd apt-repo
      - rsync -az -e "ssh -p 22 -o StrictHostKeyChecking=no" docs@ijzer:/appdata/static/apt/bullseye/amd64 .
      - apt-ftparchive packages amd64 > Packages
      - gzip -c Packages > Packages.gz
      - apt-ftparchive release . > Release
      - gpg --clearsign -o InRelease Release
      - gpg -abs -o Release.gpg Release
      - rsync -av . docs@ijzer:/appdata/static/apt/bullseye
    when:
      branch:
        - master
        - saga-watem
      event:
        exclude:
          - pull_request
