dist: bionic
language: cpp
compiler: 
  - gcc
before_install:
  - sudo apt-get remove -y libgdal1
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal-dev libwxgtk3.0-dev swig python-dev libproj-dev libvigraimpex-dev
  - cd saga-gis
  - autoreconf -fi
script: ./configure && make
