clone_folder: c:\project\saga
platform: x64
configuration: Release

environment:
  SAGA: c:\project\saga
  GDAL: C:\deps\libs4saga_x64\gdal-2.1.3
  HARU: C:\deps\libs4saga_x64\libharu-2.2.0
  LIBLAS: C:\deps\libs4saga_x64\liblas-1.2.1
  OPENCV: C:\deps\libs4saga_x64\opencv-3.1.0
  PGSQL: C:\deps\libs4saga_x64\pgsql-9.5.3
  PROJ4: C:\deps\proj4.9.3-vs140
  VIGRA: c:\deps\libs4saga_x64\vigra-1.11.0
  WXWIN: c:\deps\wxWidgets-3.1.0
  VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"

before_build:
  - cmd: mkdir c:\deps
  #get wxwidgets libs + inludes
  - ps: Start-FileDownload https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_Dev.7z
  - ps: Start-FileDownload https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0-headers.7z
  - ps: Start-FileDownload https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_Dev.7z -o%WXWIN% -bb2
  - cmd: 7z x wxWidgets-3.1.0-headers.7z -o%WXWIN% -bb2
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z -o%WXWIN% -bb2
    #small fix because wxwindows paths are different when downloading than when compiling yourself
  - cmd: move %WXWIN%\lib\vc140_x64_dll %WXWIN%\lib\vc_x64_dll
  #get libs4saga
  - ps: Start-FileDownload https://downloads.sourceforge.net/project/saga-gis/For%20Developers/libs4saga/libs4saga_20170221_x64.zip
  - cmd: 7z x libs4saga_20170221_x64.zip -oc:\deps\
  # proj4 is not used from libs4saga as this version does not work nicely with vc140
  - ps: Start-FileDownload http://gisky.be/proj4.9.3-vs140.7z
  - cmd: 7z x proj4.9.3-vs140.7z -oc:\deps
  #disable build of liblas modules as they don't work with vs 2015 yet
  - cmd: sed -i '/{315A9D51-F880-4E45-A890-60FCC4AC71DA}.*Build\.0.*/d' saga-gis/src/saga.vc10.sln
  # disable riegl import as it requires an SDK
  - cmd: sed -i '/{A89FB596-3D86-4BF0-A57B-DAC3A7D2E740}.*Build\.0.*/d' saga-gis/src/saga.vc10.sln
  #upgrade to visual studio 2015 (v14) to enable openmp
  - CALL "%VCVARS%"
  - cmd: devenv c:\project\saga\saga-gis\src\saga.vc10.sln /upgrade

build:
  project: saga-gis\src\saga.vc10.sln

after_build:
  - cmd: cp %WXWIN%/lib/vc_x64_dll/wxmsw310u_*.dll %SAGA%/saga-gis/bin/saga_vc_x64 
  - cmd: cp %WXWIN%/lib/vc_x64_dll/wxbase310u_*.dll %SAGA%/saga-gis/bin/saga_vc_x64 
  - cmd: cp -r c:\deps\libs4saga_x64\_bin\dll %SAGA%\saga-gis\bin\saga_vc_x64 
  - cmd: 7z a saga_vc_x64.7z %SAGA%\saga-gis\bin\saga_vc_x64

artifacts:
  - path: saga_vc_x64.7z
    name: saga
