FROM ubuntu:focal
RUN sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list   
RUN apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt -y install tzdata && \
    apt build-dep saga -y && apt install -y git-buildpackage
